apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bds-core-save
  labels:
    app: minecraft
  {{- with .Values.volumeAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    {{- if .Values.storage }}
      {{- if .Values.storage.size }}
      storage: {{ toString .Values.storage.size }}
      {{- else}}
      storage: 8Gi
      {{- end }}
    {{- else }}
      storage: 8Gi
    {{- end }}