apiVersion: v1
kind: Service
metadata:
  name: {{ include "bds-maneger-core.fullname" . }}
  labels:
    {{- include "bds-maneger-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" | toString }}
  ports:
    # Server V4 port
    - port: 19132
      protocol: UDP
      targetPort: server-v4
      name: server-v4

    # Server V6 port
    - port: 19133
      protocol: UDP
      targetPort: server-v6
      name: server-v6
    
    # Bds Core API Rest port
    - port: 1932
      protocol: TCP
      targetPort: bds-api
      name: bds-api
  selector:
    {{- include "bds-maneger-core.selectorLabels" . | nindent 4 }}
